_select_data:
  tamanos:
    col-12: 1 foto por linea
    col-6: 2 fotos por linea
    col-4: 3 fotos por linea 
    col-3: 4 fotos por linea

  formas:
    square: foto cuadrado
    portrait: foto vertical
    landscape: foto horizontal


    
